# Documents/cours/TP/provisioning/my_playbook.yml
---
- name: Symfony dev env (PHP, Nginx, MySQL)
  hosts: all
  gather_facts: no
  sudo: yes

  roles:
    - common
    - php-fpm
    - nginx
  #  - mysql
